language: php

php:
    - 5.6
    - 7.0
    - 7.1

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml -spn --encoding=utf-8 src/ --report-width=150

matrix:
  fast_finish: true


notifications:
    on_success: never
    on_failure: always
